---
apiVersion: v1
kind: Namespace
metadata:
  name: failed-pod
    
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-fail
  namespace: failed-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "exit 1"]

