#Role Object Configuration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role-for-kube-user
  namespace: kube-user-ns
rules:
- apiGroups:
  - "*"
  resources:
  - '*'
  verbs:
  - '*'

#RoleBinding Object Configuration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rb-for-kube-user
  namespace: kube-user-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-role-for-kube-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube-user

