#ClusterRole Object Configuration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-for-kube-user
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch

#ClusterRoleBinding Object Configuration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-for-kube-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-for-kube-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube-user


