# 1.Generate Private Key 
# openssl genrsa -out kube-user.key 2048
#
#
# 2. Create CSR for User 
# openssl req -new -key kube-user.key -out kube-user.csr -subj "/CN=kube-user/O=aaps-reader/O=app-admin" 
#
# 3. Create CSR Object

---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: kube-user-csr
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2d6Q0NBV3NDQVFBd1BqRVNNQkFHQTFVRUF3d0phM1ZpWlMxMWMyVnlNUlF3RWdZRFZRUUtEQXRoWVhCegpMWEpsWVdSbGNqRVNNQkFHQTFVRUNnd0pZWEJ3TFdGa2JXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUEzdUsyQm5LRVJLSjlXL1N4TC9VN1pVSnRhL0EyOFpBR1pQbnFwbGdaUStwdUwzSksKREZuZmNzWmhpZU03MVhUdmZmY2FiTDhOWmRnZkVSdzVHOGR3cXdiQ20zZDVOUjR1S0ZGZUJtNXBDU1ZJbUNVQQpzRGlQQmVhNUZUNUVTUHYrY0VQUCtJUFY5dlJvUlIwTW9MR1JnMUUwTUI3Y3dCSkg3VHFETWtWZGw3SE9BL2NGCjN6Z1RnUGlrZDRhZTdwbFo0c0Fxb2tLUUkvWXRPTkpQMEhIZjd2eCtMQWdOSk9SS2wzOW95dmxqNXN4VVlreGMKa3lnbnB5S3Jyd2ZhNDNaTVBnRDNrOEtuaXdxWlN0TjJTRmxzMzd0Mnd1ZWx0UFFNV1VVa3ZXaE9MeEF5ZitYQQp2S1JDdkhkZWlwUnN0bW5DVUVkY1AxK1EzVWxETTJXQkpJbFNUUUlEQVFBQm9BQXdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0VCQUZDOVdvbXgvRVJCNTVyMHNZTHZFTTZ1dERvL3JLMHJtWHhVRExwcWM2Qy9DRExXMUxEa2VENVAKNnpZUFpOOEgrZ2pUYjdib05lZVNucUFOQys4MEtOVUNXaytCdTNENzVkZ09vVTZhNWhtUHZvWldJRnJ0WngvdApXNWRDOTJXc3M0cWhWMmtIaGtkNnRQcEpGZlVmd3kvbGRiTUljWTAyUTdreEh4R0UrOTk3U0haQU8rKzhOT2dTCi9ReHVjRCtDWmRQNkpRK2ZVSWhJd0R5MlNqbkVZVkorV1lCM0RPTDBRRnZKS2NSa0kyTFlBVm1zcEorYnAyMFIKVExRR25WdVNsWFVFZ1p5WXRqUGdJMW0zL09oS0ZYUkhBRzNMNDBjbjJmdXFmbHp0OUlXTFJmSGlkVzM1Y2djegp1cmNjWlNpakF6YWZOT1pXMTEyNS9aanNiSTRlb2xZPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
...


# 4. List the CSR
#    kubectl get csr
#
# 5. Approve CSR for User
#    kubectl certificate approve kube-user-csr
#
# 6. Get the certificate
#    kubectl get csr/kube-user-csr -o yaml    ( Certificate is base64 enconded under status.certificate) 
#
# 7. Retrieve the certificate from CSR
#    kubectl get csr/kube-user-csr -o jsonpath='{.status.certificate}'| base64 -d > kube-user.crt
#
