# 1.Generate Private Key 
# openssl genrsa -out kube-user.key 2048
#
#
# 2. Create CSR for User 
# openssl req -new -key kube-user.key -out kube-user.csr -subj "/CN=kube-user/O=aaps-reader/O=app-admin" 
#
# 3. Create CSR Object

---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: kube-user-csr
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2VEQ0NBV0FDQVFBd016RVlNQllHQTFVRUF3d1BhM1ZpWlMxaFpHMXBiaTExYzJWeU1SY3dGUVlEVlFRSwpEQTV6ZVhOMFpXMDZiV0Z6ZEdWeWN6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFMUTUzMVFyb3hHUHFxMVRBdTIzNGlvNXBnVzJzMjd5TkJFZzgwWUxQY2xEOU9kaWNYNkF5V29OUkgrV0ZMM0cKZTM2RklQSkRBYTZnYkJZaWpjLzNmOWI5YTNKSU5oK0d6SFVSeHhDK0J1VmRoKzhpU0JBcjltYnUwMzBMeCtZbwpUZkRGZUNmZjBOamNaQlJjSjVrMWw5b3dYdGQwZE01VnM2WVZRYWhQMGRzelh2aTNHblF3RG5XSE1CUFVXaE5ECm9ZV1JKT1JlVERCcWRTREIyMVFPRzZhWWh6alNhbEhIYnNKckZTSmJVNzdWOGxpTlpVS2tEcjRVMDJ6VWZUMTMKVUlqRmJZQllpREU5SnVFMitlZFhNVnREajdKNXpuUTBBNzBXb3ZaVzdSYW43a3Y2bzE1SGtuSmNqUE0rTHBweApCZG11TjB0NUN6MFpKRytJb0NMNEF6VUNBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3BUcFNTCmpma3RkWU9FRHQrZ1BiZHA5MUxJMEozM0NQMVp6d2xnZ2FEeWI0WGdNWng0KzNscTFMSXdOV3dYK2EzUUhIeWMKWmV5QmpzT05qSmV6WTZXMDRRTWJYM0xKRmZHa0J1VXM5cjhLcDZLUHhYa2x6c1FEMEZBQmp2NUpuUnl6RUdtUQpFQS84cFZRQ2NHQzF6Y0NIb1JnZjVnT3dJcmZTUE15MW1RRWFhNnRmL3FLK0JTMExXYWYxYzdSNE1SMlk5NzJMCmhNSmpTRHhWQzF1TjJ5TmJzeWlJME1TTldVNVRodDFsc0d0NWpma3Y5R0FkL3p1dy9Da2ZCOVZrUWJHVWtOb0QKcDdVM3lDNUdVbG80eEVLZnRPZ2JkMlA0aTB4T3hma3ZKK3RNYkNyVXowdmx3NktpcGMrY3VxUi9Yd1VUQ2gzTwoyWVc1RXUrSTM2eXJSV3g4Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client

  expirationSeconds: 864000
  usages:
  - client auth
...


# 4. List the CSR
#    kubectl get csr
#
# 5. Approve CSR for User
#    kubectl certificate approve kube-user-csr
#
# 6. Get the certificate
#    kubectl get csr/kube-user-csr -o yaml    ( Certificate is base64 enconded under status.certificate) 
#
# 7. Retrieve the certificate from CSR
#    kubectl get csr/kube-user-csr -o jsonpath='{.status.certificate}'| base64 -d > kube-user.crt
#
