---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rb-for-kube-user
  namespace: kube-user-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-role-for-kube-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube-user
