---
apiVersion: v1
kind: Namespace
metadata:
  name: redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  serviceName: "redis-headless"
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
          - containerPort: 6379
            name: redis
          volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /mnt/redis-data
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None  # Makes it headless
  selector:
    app: redis
