---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-custom


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-nginx-config
  namespace: nginx-custom
data:
  vhost.conf: |
    server {
      listen 90;
      server_name localhost;
      root /usr/share/nginx/html;
      index index.html


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-nginx-deployment
    env: test
  name: nginx-custom-deployment
  namespace: nginx-custom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-nginx-deployment
      env: test
  template:
    metadata:
      labels:
        app: custom-nginx-deployment
        env: test
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: custom-nginx-config
          mountPath: /etc/nginx/conf.d
          subPath: nginx.conf
      volumes:
      - name: custom-nginx-config
        configMap:
          name: custom-nginx-config  
