---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    env: test
  name: nginx-deployment
  namespace: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
      env: test
  template:
    metadata:
      labels:
        app: nginx-deployment
        env: test
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
