---
apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-demo
spec:
  initContainers:
  - name: container-1
    image: busybox
    command: ["sh", "-c", "echo 'This is container 1 data' > /data/container1.txt"]
    volumeMounts:
    - name: shared-data
      mountPath: /data
  containers:
  - name: container-2
    image: busybox
    command: ["sh", "-c", "cat /data/container1.txt && sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /data
  restartPolicy: Never
  volumes:
    - name: shared-data
      emptyDir: {}


