---
apiVersion: v1
kind: Namespace
metadata:
  name: init-container-demo

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    env: dev
  name: nginx-pod
  namespace: init-container-demo
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-volume
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - |
      echo "This message is from init container" > /usr/share/nginx/html/index.html
    volumeMounts:
    - name: nginx-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-volume
    emptyDir: {}
