---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-pod

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    env: dev
  name: nginx-web
  namespace: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        cpu: 20m
        memory:  40Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5

