---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-auth


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-nginx-config
  namespace: nginx-auth
data:
  vhost.conf: |
    server {
      listen 90;
      server_name localhost;
      location / {
        root /usr/share/nginx/html;
        index index.html;
        auth_basic "Auth Required";
        auth_basic_user_file /etc/nginx/.htpasswd;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-nginx-deployment
    env: test
  name: nginx-custom-deployment
  namespace: nginx-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-nginx-deployment
      env: test
  template:
    metadata:
      labels:
        app: custom-nginx-deployment
        env: test
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: custom-nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-auth-volume
          mountPath: /etc/nginx/.htpasswd
          subPath: .htpasswd
      volumes:
      - name: custom-nginx-config
        configMap:
          name: custom-nginx-config  
      - name: nginx-auth-volume
        secret:
          secretName: nginx-auth-secret
