---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod
  name: test-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2.example.com
  containers:
  - image: nginx
    name: test-pod


