---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-affinity-other-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deployment-pod-affinity
  name: test-deployment-pod-affinity
  namespace: pod-affinity-other-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-deployment-pod-affinity
  template:
    metadata:
      labels:
        app: test-deployment-pod-affinity
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: 
                - monitoring 
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {}
      containers:
      - image: nginx
        name: nginx


