---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-affinity-monitoring

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deployment-monitoring
  name: test-deployment-monitoring
  namespace: pod-affinity-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: 
                - monitoring 
            topologyKey: kubernetes.io/hostname
      containers:
      - image: grafana/grafana
        name: monitoring

