---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-affinity

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deployment-pod-affinity
  name: test-deployment-pod-affinity
  namespace: pod-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-deployment-pod-affinity
  template:
    metadata:
      labels:
        app: test-deployment-pod-affinity
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - test-deployment-pod-affinity
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - database
              topologyKey: kubernetes.io/hostname
              namespaceSelector: {}
      containers:
      - image: nginx
        name: nginx


