---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-affinity-web-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deployment-frontend
  name: test-deployment-frontend
  namespace: pod-affinity-web-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-deployment-frontend
  template:
    metadata:
      labels:
        app: test-deployment-frontend
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: database
                operator: In
                values: 
                - redis 
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {}
      containers:
      - image: nginx
        name: web-frontend

