---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-affinity-redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    database: redis
  name: test-deployment-redis
  namespace: pod-affinity-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      database: redis
  template:
    metadata:
      labels:
        database: redis
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: database
                operator: In
                values: 
                - redis 
            topologyKey: kubernetes.io/hostname
      containers:
      - image: redis
        name: redis-cache

