---
apiVersion: v1
kind: Namespace
metadata:
  name: taints-and-tolerations

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deployment
  name: test-deployment
  namespace: taints-and-tolerations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1.example.com 
      tolerations:
      - key: kubernetes.io/hostname
        operator: Equal
        value: worker1.example.com
        effect: NoSchedule
      containers:
      - image: nginx
        name: nginx
