---
apiVersion: v1
kind: Namespace
metadata:
  name: node-affinity

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deployment
  name: test-deployment
  namespace: node-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1.example.com
                - worker3.example.com
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: purpose
                operator: In
                values:
                - performance
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 20m
            memory : 20Mi
          limits:
            cpu: 50m
            memory: 50Mi


