---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-virtual-routing


# ConfigMap for nginx vhost configs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-web2
  namespace: ingress-virtual-routing
data:
  vhost.conf: |
    server {
      listen 8080;
      #server_name localhost;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }   
    }


# ConfigMap for index.html file #    
---
apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to Online Shop</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f9;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
            }
            .content {
                text-align: center;
                padding: 30px;
                background-color: #ffffff;
                box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
                border-radius: 8px;
            }
            h1 {
                color: #333;
                font-size: 36px;
            }
            p {
                color: #666;
                font-size: 18px;
            }
        </style>
    </head>
    <body>
        <div class="content">
            <h1>Welcome to Online Shopping on HOST web2.example.com</h1>
            <p>Your one-stop shop for all your needs!</p>
        </div>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: html-file2
  namespace: ingress-virtual-routing


# NGINX Deployment with 1 replicas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment-web2
    env: test
  name: nginx-deployment-web2
  namespace: ingress-virtual-routing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment-web2
      env: test
  template:
    metadata:
      labels:
        app: nginx-deployment-web2
        env: test
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config-web2
          mountPath: /etc/nginx/conf.d
        - name: nginx-html-file2
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config-web2
        configMap:
          name: nginx-config-web2  
      - name: nginx-html-file2
        configMap:
          name: html-file2

# Service to expose NGINX deployment
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deployment-web2
    env: test
  name: web-service-2
  namespace: ingress-virtual-routing
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-deployment-web2
    env: test
  type: ClusterIP
